name: Remix on Github Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  build-deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: install dependencies
        run: npm install
        working-directory: ./remix-app

      - name: Start server and download static content with wget
        run: |
              npm run dev &
              sleep 10 &&
              wget --mirror --directory-prefix=public --no-host-directories --page-requisites --adjust-extension --convert-links --no-parent http://localhost:3000
        working-directory: ./remix-app

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          publish_dir: ./public
          external_repository: s4na/remix-github-pages-example
